### ISSUE TITLE
Search freezing issue

### ISSUE THREAD

**Issue by PartialShawn** [ShawnPConroy/globasa-dictionary#2]
On some computers the search will 'freeze' as the user is typing in a search term. Possible fixes include:

* JavaScript array of terms for faster access (no DOM).
* No searching until user presses enter/submit.
* No searching until length is 3+ (or has stopped typing for 1+ second)
* Don't search until user hasn't typed anything for half a second or so.

**Comment by Ektor760** [comment]
I would say, No searching until user presses enter/submit.

-Ektor

**Comment by PartialShawn** [comment]
No longer uses AJAX to filter page content.
