### ISSUE TITLE
Speed up load time

### ISSUE THREAD

**Issue by PartialShawn** [ShawnPConroy/globasa-dictionary#3]
Speed up load time by redesigning how it works.

What are the requirements?

* Do we ever need more than one word? Dictionary.com never shows more than a single world on the screen. Both [Merriam-Webster](https://www.merriam-webster.com/dictionary/framd) and [Dictionary.com](https://www.dictionary.com/misspelling?term=fram) search errors go to a misspelling page that finds similar words.
* Do we want auto-complete like Merriam-Webster, or show a failed search like Dictionary.com?
* Do we want a full word list ever? Maybe only in a special mode?

Possible solutions:
* pre-rendering each entry.
* If possible, pre-render entire word list for display and array variables. This may help for the entire word list, but may not for an individual word.
* Use auto-complete instead of filtering the search results live

For speed an easy of creation the Dictionary.com model would be easiest and fastest for me to do. However, it would be more of an interesting challenge to do the Merriam-Webster style because AJAX and JavaScript UI is not my forte.

I suspect that it would be best to change over to the dictionary.com method to get it work. We can add Merriam-Webster method later. That would be the fastest solution.

**Comment by PartialShawn** [comment]
May effect #2 if we Switch to the Dictionary.com model.

**Comment by Ektor760** [comment]
Hi Shawn,

No need for more than one word. 
show a failed search like Dictionary.com
Full word list only in a special mode

Yes, I agree. dictionary.com style first, and then perhaps Merriam-Webster method later. 

Xukra!
