### ISSUE TITLE
Seperate Globasa and English search boxes

### ISSUE THREAD

**Issue by PartialShawn** [ShawnPConroy/globasa-dictionary#4]
From Hector:
> wouldn't it better to have an input box for Globasa and another one for English? Some words look identical.

Example:
* English hare (_kargux_).
* Globasa _hare_ (have).

While more complex (people would have to choose the right box) it would mean better results.

But then when looking at the dictionary in Globasa localization there would need to be only a single search bar because you are only searching for the word.

**Comment by Ektor760** [comment]
Shawn: "But then when looking at the dictionary in Globasa localization there would need to be only a single search bar because you are only searching for the word."

Correct.

**Comment by PartialShawn** [comment]
New search box no longer has the problems of the old system. Does it work well now, or should there still be a solid wall between searching Globasa words and searching your current language (usually English during testing).

**Comment by PartialShawn** [comment]
[](url)
