### ISSUE TITLE
Match filtering

### ISSUE THREAD

**Issue by PartialShawn** [ShawnPConroy/globasa-dictionary#8]
Hector:
> And is there a way to omit anything that's not relevant o the exact match? For example if I enter "is", the program will generate a list of a bunch of other words that aren't relevant: hisi, etc.

Possible solutions:
* Matches must be from the start of the word.
* Don't start filter/search until 3 letters are typed

Or is this only for when there is an exact match?

**Comment by Ektor760** [comment]
I would say, Matches must be from the start of the word.

I'm not understanding this questions: "Or is this only for when there is an exact match?"

-Ektor

**Comment by PartialShawn** [comment]
No longer filtering, using the new search controller.
